Update copyright, bump version to 0.11.2, fix exits, fix libdir for 64 bits

diff --git a/celt.SlackBuild b/celt.SlackBuild
--- a/celt.SlackBuild
+++ b/celt.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # Slackware build script for CELT
-# Copyright (C) 2010,2011 Georgi D. Sotirov <gdsotirov@dir.bg>
+# Copyright (C) 2010-2012 Georgi D. Sotirov <gdsotirov@dir.bg>
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -19,13 +19,13 @@
 #
 # Visit SlackPack at http://sotirov-bg.net/slackpack/
 #
-# $Id: celt.SlackBuild,v 1.3 2011/09/10 17:22:25 gsotirov Exp $
+# $Id: celt.SlackBuild,v 1.4 2012/09/02 20:48:19 gsotirov Exp $
 #
 
 . ../../slack-package.conf
 
 NAME=celt
-VERSION=0.11.1
+VERSION=0.11.2 # tandem test fails with 0.11.3
 BUILD=${BUILD:-1}
 ARCH=${ARCH:-i486}
 
@@ -51,26 +51,28 @@ mkdir -p $PKG
 
 # Extract the source
 cd $TMP
-tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 1
+tar -xvf $CWD/$NAME-$VERSION.tar.?z* || exit 3
 cd $SRC fix_source
 
 # Configure
-CFLAGS=$SLKCFLAGS \
-CXXFLAGS=$SLKCFLAGS \
+CFLAGS="$SLKCFLAGS -O2" \
+CXXFLAGS="$SLKCFLAGS -O2" \
 ./configure --build=$ARCH-slackware-linux \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
+            --libdir=/usr/lib${LIBDIRSUFFIX} \
             --sysconfdir=/etc \
             --localstatedir=/var \
             --enable-shared=yes \
             --enable-static=no \
-            --enable-assertions || exit 2
+            --enable-assertions || exit 4
 
 # Build, check & install
-make -j4 || exit 3 
-make check || exit 4
-make DESTDIR=$PKG install || exit 5
+make -j4 || exit 5
+make check || exit 6
+make DESTDIR=$PKG install || exit 7
 
+# Prepare
 bin_perms $PKG
 ( cd $PKG; strip_bin; strip_lib )
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
@@ -84,6 +86,7 @@ install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -91,6 +94,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
